apiVersion: apps/v1
kind: Deployment
metadata:
  name: general-store-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: general-store-mongo
  template:
    metadata:
      labels:
        app: general-store-mongo
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
---
apiVersion: v1
kind: Service
metadata:
  name: general-store-mongo
spec:
  selector:
    app: general-store-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

